# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["CNAME", "README.md", "LICENSE"]
paginate: 5
paginate_path: ":num"
permalink: pretty
sass:
    style: :compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Custom Variables
analytics: 100929437
author:
  email: "mengrui6351@gmail.com"
  github: "Corleno/"
  linkedin: "Rui Meng"
  name: "Rui Meng"
  uri: "http://Corleno.github.io"
description: "Personal website of Rui Meng, PH.D. in Statistics."
title: "Rui Meng"
url: "http://Corleno.github.io"

theme: jekyll-theme-merlot